### ISSUE TITLE
people need to see apple

### ISSUE THREAD

**Issue by hzrd149** [ItsDeadPixel/AI-Interaction-Game#3]
just an idea but i think the people should go for the apple if they like you enough, and maybe draw there happiness above there head.

**Comment by ItsDeadPixel** [comment]
There's something I can do. They'll just run for it if they're close enough. Sight range will increase with happiness.

**Comment by hzrd149** [comment]
well you doint have to fix it now, notice that this is tagged "enhancement"

**Comment by ItsDeadPixel** [comment]
I know. I'm already doing it though. Every little detail counts.

Here's how it'll work. The default view range is 20 pixels. Very short. (could be increased) However, the view range is calculated like this...

(Default view range) + (Personal happiness \* 2)

so with an increased happiness rating for said person, the view range is extended for that person by their happiness \* 2.

So this is the first happiness benefit. only affects individual Life forms though. Others could affect all LFs.

**Comment by hzrd149** [comment]
sounds good.
and is it possible to draw the personal happiness above there head?

**Comment by ItsDeadPixel** [comment]
I can get to that. I had another idea for a selector tool. I'll add it to the improvements so you can see what I mean.
