### ISSUE TITLE
the ! dont follow the people

### ISSUE THREAD

**Issue by hzrd149** [ItsDeadPixel/AI-Interaction-Game#4]
the ! dont follow the people and if they did i think they should stay on longer.

**Comment by ItsDeadPixel** [comment]
Another issue I meant to fix, however, I'm temporarily brain dead at the moment on how to fix it... xD

**Comment by hzrd149** [comment]
make a var on the !, and set that var to the person it follows.
then on the step event of the ! it will go to that persons x.
and set the var right after you create the ! obj

**Comment by ItsDeadPixel** [comment]
I think this is one you'd have to do... how could I make it follow one specific AI when there are dozens? I'm sure I've done this before, but I can't remember how.

**Comment by hzrd149** [comment]
ok ill fix it, the issue is now assigned to me

**Comment by ItsDeadPixel** [comment]
There's still a bug in it. the game aborts when an AI falls off the world when a ! is still active. Need to destroy the ! when the AI is destroyed.

**Comment by hzrd149** [comment]
on it
